// <auto-generated />
namespace LojaVirtual.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Att_TabelaProduto_DataAnnotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Att_TabelaProduto_DataAnnotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201608190248058_Att_TabelaProduto_DataAnnotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
